---
- hosts: cisco 
  connection: local
  gather_facts: False
  ignore_errors: yes

  vars:
    cli:
        host: "{{ host }}"
        username: "{{ username }}"
        password: "{{ password }}"

  tasks:
    - name: Gather IOS Facts using the Ansible IOS Facts Module
      ios_facts:
        provider: "{{ cli }}"

      register: facts_output

    - debug: var=facts_output
    - debug: var=facts_output.ansible_facts.ansible_net_version

    - local_action: copy content="{{ output }}" dest="./FACTs/{{ inventory_hostname }}.txt"
