---
- name: collect device facts and display OS version
  # hosts: "{{ inventory | default('all') }}"
  hosts: cisco
  gather_facts: false
  connection: local
  ignore_errors: yes
  
  vars:
    cli:
        host: "{{ host }}"
        username: "{{ username }}"
        password: "{{ password }}"
    
  tasks:
    - nxos_facts:
        provider: "{{ cli }}" 

      register: facts_output      
    
    - debug: var=facts_output.ansible_facts.ansible_net_hostname
    - debug: var=facts_output.ansible_facts.ansible_net_version
    - debug: var=facts_output.ansible_facts.ansible_net_model   

    - name: write the inventory in into file      
      copy: content="{{ facts_output.ansible_facts.ansible_net_hostname, facts_output.ansible_facts.ansible_net_version , facts_output.ansible_facts.ansible_net_model }}" dest="facts/{{ inventory_hostname }}.txt"