---

- name: Another way of obtaining show commands and backups
  hosts: cisco
  connection: local
  gather_facts: False
  ignore_errors: yes

  vars:
    cli:
        host: "{{ host }}"
        username: "{{ username }}"
        password: "{{ password }}"

  tasks:

    - name: Show IP Interface Brief
      ios_command:
        commands:
           - show ip int br
           - show inventory
        provider: "{{ cli }}"

      register: intbr

    - debug: var=intbr.stdout_lines

    - name: Save Show Command output
      copy:
        content: "{{ intbr.stdout }}"
        dest: "./SHOW/{{ inventory_hostname }}.log"


    - name: Backup a configuration on a device
      ios_config:
        provider: "{{ cli }}"
        backup: yes

      register: bkup

    - debug: var=bkup

