---

- hosts: cisco
  connection: local
  gather_facts: False
  ignore_errors: yes


  tasks:

    - name: Show IP Interface Brief
      ios_command:
        commands:
           - show ip int br
           - show inventory
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"

      register: intbr

    - debug: var=intbr.stdout_lines

    - name: Save Show Command output
      copy:
        content: "{{ intbr.stdout }}"
        dest: ./SHOW/{{ inventory_hostname }}.log"


    - name: Backup a configuration on a device
      ios_template:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        backup: true
        src: ntp.j2


      register: bkup

    - debug: var=bkup.stdout_lines

